### PR TITLE
Support connect to lsp-bridge server running in devcontainer

### PR DESCRIPTION
**Pull request by nohzafk**
Long story short, here are screenshots of lsp-bridge connecting to lsp-bridge server running inside [devcontainer](https://containers.dev/), this will definitely help the editing expereince of using Emacs to access files inside docker container.

## running on `emacs -q`

Screenshot 2024-06-08 at 6 40 21 PM

## running on `doom-emacs`

Screenshot 2024-06-09 at 4 08 41 PM

## instructions
Please see [my other project](https://github.com/nohzafk/devcontainer-feature-emacs-lsp-bridge) about the instructions of using lsp-bridge in devcontainer.

## curent limitation
When container is restarted, opened buffers are no longer valid, automatically reconnect like `open remote SSH file` is not supported.

### CODE REVIEW

**Comment by manateelazycat** [comment]
Wow, man, you are awesome!!!

**Comment by nohzafk** [comment]
that's quick! I will now point the devcontainer lsp-bridge feature to this repo master branch

**Comment by nohzafk** [comment]
Hopefully after some testing we can write about this feature in the README

**Comment by manateelazycat** [comment]
> Hopefully after some testing we can write about this feature in the README

Sure, you're welcome. ;)

**Comment by manateelazycat** [comment]
> that's quick! I will now point the devcontainer lsp-bridge feature to this repo master branch

I just finish csharp-ls support, this patch is awesome!

**Comment by nohzafk** [comment]
now lsp-bridge in devcontainer is pointed to master branch [d4e3534](https://github.com/manateelazycat/lsp-bridge/commit/d4e3534c4b3e1ea6eb59286e3937c4eef035c30c)

**Pull request merged**
