### PR TITLE
Update README.md (fixed 'Supported language servers' table)

### PR DESCRIPTION
**Pull request by neuromagus**
Languages are sorted by alphabetical order (lsp-servers too), removed duplicates (Latex - say 'hi'). Programming languages set first in the table (IMO, I look my programming language first, later - LSP and notes, instructions etc).

My perfectionist is happy now ;}

P.S. Sorry for my Eng.

### CODE REVIEW

**Comment by neuromagus** [comment]
P.P.S. IMHO, this Readme so long, maybe need add link for most needed Paragraphs? I mean - on top after buttons (with 'test passing' and change language)? for fast access to command, keys, list of languages and LSP servers?.. Well, it's just a suggestion.

**Comment by manateelazycat** [comment]
@neuromagus Can you help me sort language in README.zh-CN.md ?

**Comment by manateelazycat** [comment]
> P.P.S. IMHO, this Readme so long, maybe need add link for most needed Paragraphs? I mean - on top after buttons (with 'test passing' and change language)? for fast access to command, keys, list of languages and LSP servers?.. Well, it's just a suggestion.

Long README is ok, all document list in README is FAQ, user don't know how to do if we use top button hide it.

**Comment by neuromagus** [comment]
@manateelazycat why not? I help with README.zh-CN.md too ;}

**Comment by neuromagus** [comment]
@manateelazycat, [Done](https://github.com/manateelazycat/lsp-bridge/pull/902)

**Comment by neuromagus** [comment]
and what is mean? (yellow line)?
20240403_13h13m36s_grim

**Pull request merged**
