### PR TITLE
Feat add tabbyml support

### PR DESCRIPTION
**Pull request by sawyerzheng**
1. add a tabbyml support by using [tabby.el](https://github.com/alan-w-255/tabby.el) as a client for sending request to tabby-agent
  Notice:  tabby.el provide a tabby-mode which is laggy which use overlay and post-command-hook when used together with lsp-bridge directly, So I write this backend for acm.el.
2. tabby completion result maybe too late for the users completion, so I add a function `acm-backend-tabby-find-max-common` to drop the common suffix for users input and the prefix of the tabby's completion, eg: to write a bubble sort function
   (1) the user type: `def bubb`
   (2) trigger tabby completion
   (3) the user contine typing: `def bubble_s`
   (4) the tabby completion finished: `le_sort(arr):`
   (5) merge the input and the completion:  `def bubble_sort(arr):`
   
3. **How to enable**: 
    (1) `acm-backend-tabby` set to t
    (2) deploy your tabbyml/tabby server, reference: [tabbyml/tabby](https://tabby.tabbyml.com/docs/welcome/)
    (3) install [tabby.el](https://github.com/alan-w-255/tabby.el)
    (4) on your computer which run emacs,  [setup tabby-agent's config](https://tabby.tabbyml.com/docs/extensions/configurations/)
    (5) You don't need to install a tabby-agent directly, as tabbly.el itself distributed with the tabby-agent's javascript codes.
    
4. preview:

image

 Maybe the tabby its own problem or I used a basic model deepseek-1.3B, the completion is Not a full function.

### CODE REVIEW

**Comment by manateelazycat** [comment]
Thanks

**Comment by Y0ngg4n** [comment]
@sawyerzheng
When using doom doctor:
```
Checking Doom Emacs...
  x There was an unexpected runtime error
    Message: File is missing
    Details: ("Cannot open load file" "No such file or directory" "acm-backend-tabby")
    Backtrace:
      (require acm-backend-tabby)
      (load-with-code-conversion "/home/yonggan/.config/emacs/.local/straight/build-29.4/lsp-bridge/acm/acm.el" "/home/yonggan/.config/emacs/.local/straight/build-29.4/lsp-bridge/acm/acm.el" nil t)
      (require acm)
      (load-with-code-conversion "/home/yonggan/.config/emacs/.local/straight/build-29.4/lsp-bridge/lsp-bridge-code-action.el" "/home/yonggan/.config/emacs/.local/straight/build-29.4/lsp-bridge/lsp-bridge-c...
      (require lsp-bridge-code-action)
      (load-with-code-conversion "/home/yonggan/.config/emacs/.local/straight/build-29.4/lsp-bridge/lsp-bridge.el" "/home/yonggan/.config/emacs/.local/straight/build-29.4/lsp-bridge/lsp-bridge.el" t t)
      (require lsp-bridge nil t)
      (not (require 'lsp-bridge nil t))
      (if (not (require 'lsp-bridge nil t)) (display-warning 'use-package (format "Cannot load %s" 'lsp-bridge) :error) (condition-case err (progn (setq lsp-bridge-enable-log nil) (setq lsp-bridge-find-def-...
      (condition-case err (if (not (require 'lsp-bridge nil t)) (display-warning 'use-package (format "Cannot load %s" 'lsp-bridge) :error) (condition-case err (progn (setq lsp-bridge-enable-log nil) (setq ...
      (load-with-code-conversion "/home/yonggan/.config/doom/config.el" "/home/yonggan/.config/doom/config.el" t t)
      (load "/home/yonggan/.config/doom/config" t nomessage)
```

**Comment by Y0ngg4n** [comment]
@sawyerzheng nop rebuild did not fixed it. What recipe are you meaning? Of tabby?

**Comment by sawyerzheng** [comment]
@Y0ngg4n My straight recipe:

(use-package tabby
  :straight (tabby
             :type git
             :host github
             :files ("*.el" "node_scripts")
             :repo "alan-w-255/tabby.el")
  :commands (tabby-mode)
 )

**Pull request merged**
