### PR TITLE
Add eclipse.jdt.ls template.

### PR DESCRIPTION
**Pull request by EdmondFrank**

### CODE REVIEW

**Comment by wsw0108** [comment]
jdt-ls already has a python launcher script :)

**Comment by archer-n** [comment]
> Choose a value for `-data`: the absolute path to the data directory. `eclipse.jdt.ls` stores workspace specific information in it. Each "workspace/project" should be unique.

It needs to be different for each project, and there should be problems with hard writing /tmp/cache.

**Comment by EdmondFrank** [comment]
> jdt-ls already has a python launcher script :)
> 
> https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script

Thanks man.

**Comment by EdmondFrank** [comment]
> > Choose a value for `-data`: the absolute path to the data directory. `eclipse.jdt.ls` stores workspace specific information in it. Each "workspace/project" should be unique.
> 
> It needs to be different for each project, and there should be problems with hard writing /tmp/cache.
Use [wrapper-script](https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script) can solve this problem.

**Comment by archer-n** [comment]
> > > Choose a value for `-data`: the absolute path to the data directory. `eclipse.jdt.ls` stores workspace specific information in it. Each "workspace/project" should be unique.
> > 
> > 
> > It needs to be different for each project, and there should be problems with hard writing /tmp/cache.
> > Use [wrapper-script](https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script) can solve this problem.

In fact, there is no -data configuration in [wrapper-script](https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script)  , and users still need to specify it themselves. Waiting for a [“More flexable configuration?“](https://github.com/manateelazycat/lsp-bridge/issues/19) See if there is a solution after this is resolved. Currently, I can only use local custom configuration files.

The following is my eglot's java configuration:
      - lombok needs to specify my local jar path
      - The path of "-data" needs to be unique for each project
      - Specifying "-configuration" is to not pollute the files in the jdtls project. This is mentioned in the jdtls documentation.

```elisp
(defun eglot--eclipse-jdt-contact (interactive)
    "Return cons (CLASS . ARGS) for connecting to Eclipse JDT.
If INTERACTIVE, prompt user for details."
    (let ((lombok-jar-path (expand-file-name "~/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar")))
      (cons 'eglot-eclipse-jdt
            (list
             "jdtls"
             (concat "--jvm-arg=-javaagent:" lombok-jar-path)
             " -configuration" (expand-file-name "~/.cache/jdtls")
             "-data" (eglot-java-workspace-dir)
             ))))
```

**Comment by EdmondFrank** [comment]
> > > > Choose a value for `-data`: the absolute path to the data directory. `eclipse.jdt.ls` stores workspace specific information in it. Each "workspace/project" should be unique.
> > > 
> > > 
> > > It needs to be different for each project, and there should be problems with hard writing /tmp/cache.
> > > Use [wrapper-script](https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script) can solve this problem.
> 
> In fact, there is no -data configuration in [wrapper-script](https://github.com/eclipse/eclipse.jdt.ls#running-from-command-line-with-wrapper-script) , and users still need to specify it themselves. Waiting for a [“More flexable configuration?“](https://github.com/manateelazycat/lsp-bridge/issues/19) See if there is a solution after this is resolved. Currently, I can only use local custom configuration files.
> 
> The following is my eglot's java configuration: - lombok needs to specify my local jar path - The path of "-data" needs to be unique for each project - Specifying "-configuration" is to not pollute the files in the jdtls project. This is mentioned in the jdtls documentation.
> 
> ```emacs-lisp
> (defun eglot--eclipse-jdt-contact (interactive)
>     "Return cons (CLASS . ARGS) for connecting to Eclipse JDT.
> If INTERACTIVE, prompt user for details."
>     (let ((lombok-jar-path (expand-file-name "~/.m2/repository/org/projectlombok/lombok/1.18.22/lombok-1.18.22.jar")))
>       (cons 'eglot-eclipse-jdt
>             (list
>              "jdtls"
>              (concat "--jvm-arg=-javaagent:" lombok-jar-path)
>              "-configuration" (expand-file-name "~/.cache/jdtls")
>              "-data" (eglot-java-workspace-dir)
>              ))))
> ```

In `jdtls`, it would auto resolve config path.
For data directory, you are right. Maybe we need do some impovement in the future. Now it would `jdtls` current directory as data directory and not unique for each project.
```python
def get_shared_config_path(jdtls_base_path):
	system = platform.system()

	if system == 'Linux':
		config_dir = 'config_linux'
	elif system == 'Darwin':
		config_dir = 'config_mac'
	elif system == 'Windows':
		config_dir = 'config_win'
	else:
		raise Exception("Unknown platform {} detected".format(platform))

	return jdtls_base_path / config_dir

def main(args):
	parser = argparse.ArgumentParser()
	parser.add_argument("--validate-java-version", default=True, action=argparse.BooleanOptionalAction)
	parser.add_argument("--jvm-arg",
			default=[],
			action="append",
			help="An additional JVM option (can be used multiple times. Note, use with equal sign. For example: --jvm-arg=-Dlog.level=ALL")

	known_args, args = parser.parse_known_args(args)
	java_executable = get_java_executable(known_args.validate_java_version)

	jdtls_base_path = Path(__file__).parent.parent
	shared_config_path = get_shared_config_path(jdtls_base_path)
	jar_path = find_equinox_launcher(jdtls_base_path)

	os.execvp(java_executable,
		["-Declipse.application=org.eclipse.jdt.ls.core.id1",
		"-Dosgi.bundles.defaultStartLevel=4",
		"-Declipse.product=org.eclipse.jdt.ls.core.product",
		"-Dosgi.checkConfiguration=true",
		"-Dosgi.sharedConfiguration.area=" + str(shared_config_path),
		"-Dosgi.sharedConfiguration.area.readOnly=true",
		"-Dosgi.configuration.cascaded=true",
		"-noverify",
		"-Xms1G",
		"--add-modules=ALL-SYSTEM",
		"--add-opens", "java.base/java.util=ALL-UNNAMED",
		"--add-opens", "java.base/java.lang=ALL-UNNAMED"]
		+ known_args.jvm_arg
		+ ["-jar", jar_path] + args)
```

**Pull request merged**
